load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

# You don't need these variables, but are useful for configurability.
# Feel free to hardcode these values in the maybe http_archive below.
#rules_hdl_git_hash = "{LATEST_HASH}"
#rules_hdl_git_sha256 = "{LATEST_SHA}"
rules_hdl_git_hash = "ca650bf03bb635295a8a91fe743ef3dbb342605e"
rules_hdl_git_sha256 = "192396f1f889c9deee57ce292c0e4ffe51edea7894dc4e84d1f786ec7e724e3c"

maybe(
    http_archive,
    name = "rules_hdl",
    sha256 = rules_hdl_git_sha256,
    strip_prefix = "bazel_rules_hdl-%s" % rules_hdl_git_hash,
    urls = [
        "https://github.com/hdl/bazel_rules_hdl/archive/%s.tar.gz" % rules_hdl_git_hash,
    ],
)

load("@rules_hdl//dependency_support:dependency_support.bzl", rules_hdl_dependency_support = "dependency_support")
rules_hdl_dependency_support()

load("@rules_hdl//:init.bzl", rules_hdl_init = "init")
rules_hdl_init()
